<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="two_dof_arm">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="mass1" value="10" /> <!-- arbitrary value for mass -->
    <xacro:property name="width1" value="1.0" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="height1" value="0.5" /> <!-- Base Link -->
    
    <xacro:include filename="$(find two_dof_arm)/urdf/links.xacro"/>
    <xacro:include filename="$(find two_dof_arm)/urdf/camera.xacro"/>
    <xacro:include filename="$(find two_dof_arm)/urdf/colors.gazebo" />

    <link name="world"></link>

    <joint name="base_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        
    </joint>

    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 ${height1/2}" rpy="0.0 0.0 0.0"/>
            <mass value="${mass1}"/>
            <inertia
                ixx="${mass1 / 12.0 * (width1*width1 + height1*height1)}" ixy="0.0" ixz="0.0"
                iyy="${mass1 / 12.0 * (height1*height1 + width1*width1)}" iyz="0.0"
                izz="${mass1 / 12.0 * (width1*width1 + width1*width1)}"/>
        </inertial>
        <visual name="">
            <origin xyz="0.0 0.0 ${height1/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${width1} ${width1} ${height1}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${height1/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${width1} ${width1} ${height1}"/>
            </geometry>
        </collision>
    </link>
    <xacro:links /> 
    <xacro:camera />
    


</robot>